version: "3"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    restart: always
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/code
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
  bot:
    build: .
    command: python bot.py
    depends_on:
      - db
      - redis
    env_file:
      - .env